on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  run-unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: repo-checkout
        uses: actions/checkout@v5.0.0
      
      - name: set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install environment requirements
        run: pip install -r requirements.txt
      
      - name: run unit tests
        run: |
          cd tests/unit-tests
          pytest extraction_unit_testing.py transformation_unit_testing.py loading_unit_testing.py

  run-integration-testing:
    runs-on: ubuntu-latest
    steps:
      - name: repo-checkout
        uses: actions/checkout@v5.0.0
      
      - name: set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install environment requirements
        run: pip install -r requirements.txt
      
      - name: run integration tests
        run: |
          cd tests/integeration-testing
          pytest extraction_integeration_testing.py transformation_integeration_testing.py loading_integeration_testing.py